<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\Hash;

class CreateRefKegiatanTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('ref_kegiatan', function (Blueprint $table) {
					$table->integer('permen_ver')->unsigned();
					$table->integer('urusan_kode')->unsigned();
					$table->integer('bidang_kode')->unsigned();
					$table->integer('program_kode')->unsigned();
					$table->integer('kegiatan_kode')->unsigned();
					$table->text('kegiatan_nama');
					$table->timestamps();

					$foreign = [
						'permen_ver', 
						'urusan_kode',
						'bidang_kode',
						'program_kode',
						'kegiatan_kode',
					];

					$table->primary($foreign, 'permen_kegiatan_kode');
					array_pop($foreign);
					$table->foreign($foreign, 'foreign_kegiatan')->references($foreign)->on('ref_program')->onDelete('cascade')->onUpdate('cascade');
        });
				DB::table('ref_kegiatan')->insert([
					['permen_ver' => 1, 'urusan_kode' => '0', 'bidang_kode' => '0', 'program_kode' => '1', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
['permen_ver' => 1, 'urusan_kode' => '0', 'bidang_kode' => '0', 'program_kode' => '1', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Administrasi Keuangan Perangkat Daerah'],
['permen_ver' => 1, 'urusan_kode' => '0', 'bidang_kode' => '0', 'program_kode' => '1', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Administrasi Barang Milik Daerah pada Perangkat Daerah'],
['permen_ver' => 1, 'urusan_kode' => '0', 'bidang_kode' => '0', 'program_kode' => '1', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Administrasi Pendapatan Daerah Kewenangan Perangkat Daerah'],
['permen_ver' => 1, 'urusan_kode' => '0', 'bidang_kode' => '0', 'program_kode' => '1', 'kegiatan_kode' => '205', 'kegiatan_nama' => 'Administrasi Kepegawaian Perangkat Daerah'],
['permen_ver' => 1, 'urusan_kode' => '0', 'bidang_kode' => '0', 'program_kode' => '1', 'kegiatan_kode' => '206', 'kegiatan_nama' => 'Administrasi Umum Perangkat Daerah'],
['permen_ver' => 1, 'urusan_kode' => '0', 'bidang_kode' => '0', 'program_kode' => '1', 'kegiatan_kode' => '207', 'kegiatan_nama' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
['permen_ver' => 1, 'urusan_kode' => '0', 'bidang_kode' => '0', 'program_kode' => '1', 'kegiatan_kode' => '208', 'kegiatan_nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
['permen_ver' => 1, 'urusan_kode' => '0', 'bidang_kode' => '0', 'program_kode' => '1', 'kegiatan_kode' => '209', 'kegiatan_nama' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
['permen_ver' => 1, 'urusan_kode' => '0', 'bidang_kode' => '0', 'program_kode' => '1', 'kegiatan_kode' => '210', 'kegiatan_nama' => 'Peningkatan Pelayanan BLUD'],
['permen_ver' => 1, 'urusan_kode' => '0', 'bidang_kode' => '0', 'program_kode' => '1', 'kegiatan_kode' => '211', 'kegiatan_nama' => 'Administrasi Keuangan dan Operasional Kepala Daerah dan Wakil Kepala Daerah'],
['permen_ver' => 1, 'urusan_kode' => '0', 'bidang_kode' => '0', 'program_kode' => '1', 'kegiatan_kode' => '212', 'kegiatan_nama' => 'Fasilitasi Kerumahtanggaan Sekretariat Daerah'],
['permen_ver' => 1, 'urusan_kode' => '0', 'bidang_kode' => '0', 'program_kode' => '1', 'kegiatan_kode' => '213', 'kegiatan_nama' => 'Penataan Organisasi'],
['permen_ver' => 1, 'urusan_kode' => '0', 'bidang_kode' => '0', 'program_kode' => '1', 'kegiatan_kode' => '214', 'kegiatan_nama' => 'Pelaksanaan Protokol dan Komunikasi Pimpinan'],
['permen_ver' => 1, 'urusan_kode' => '0', 'bidang_kode' => '0', 'program_kode' => '1', 'kegiatan_kode' => '215', 'kegiatan_nama' => 'Layanan Keuangan dan Kesejahteraan DPRD'],
['permen_ver' => 1, 'urusan_kode' => '0', 'bidang_kode' => '0', 'program_kode' => '1', 'kegiatan_kode' => '216', 'kegiatan_nama' => 'Layanan Administrasi DPRD'],

					['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '1', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengelolaan Pendidikan Sekolah Dasar'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '1', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pengelolaan Pendidikan Sekolah Menengah Pertama'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '1', 'program_kode' => '2', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pengelolaan Pendidikan Anak Usia Dini (PAUD)'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '1', 'program_kode' => '2', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Pengelolaan Pendidikan Nonformal/Kesetaraan'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '1', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penetapan Kurikulum Muatan Lokal Pendidikan Dasar'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '1', 'program_kode' => '3', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penetapan Kurikulum Muatan Lokal Pendidikan Anak Usia Dini dan Pendidikan Nonformal'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '1', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pemerataan Kuantitas dan Kualitas Pendidik dan Tenaga Kependidikan bagi Satuan Pendidikan Dasar, PAUD, dan Pendidikan Nonformal/Kesetaraan'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '1', 'program_kode' => '5', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penerbitan Izin Pendidikan Dasar yang Diselenggarakan oleh Masyarakat'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '1', 'program_kode' => '5', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penerbitan Izin PAUD dan Pendidikan Nonformal yang Diselenggarakan oleh Masyarakat'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '1', 'program_kode' => '6', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pembinaan, Pengembangan dan Perlindungan Bahasa dan Sastra yang Penuturannya dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '2', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyediaan Fasilitas Pelayanan Kesehatan untuk UKM dan UKP Kewenangan Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '2', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penyediaan Layanan Kesehatan untuk UKM dan UKP Rujukan Tingkat Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '2', 'program_kode' => '2', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Penyelenggaraan Sistem Informasi Kesehatan secara Terintegrasi'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '2', 'program_kode' => '2', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Penerbitan Izin Rumah Sakit Kelas C, D dan Fasilitas Pelayanan Kesehatan Tingkat Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '2', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pemberian Izin Praktik Tenaga Kesehatan di Wilayah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '2', 'program_kode' => '3', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Perencanaan Kebutuhan dan Pendayagunaan Sumberdaya Manusia Kesehatan untuk UKP dan UKM di Wilayah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '2', 'program_kode' => '3', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pengembangan Mutu dan Peningkatan Kompetensi Teknis Sumber Daya Manusia Kesehatan Tingkat Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '2', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pemberian Izin Apotek, Toko Obat, Toko Alat Kesehatan dan Optikal, Usaha Mikro Obat Tradisional (UMOT)'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '2', 'program_kode' => '4', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pemberian Sertifikat Produksi untuk Sarana Produksi Alat Kesehatan Kelas 1 tertentu dan Perbekalan Kesehatan Rumah Tangga Kelas 1 Tertentu Perusahaan Rumah Tangga'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '2', 'program_kode' => '4', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Penerbitan Sertifikat Produksi Pangan Industri Rumah Tangga dan Nomor P-IRT sebagai Izin Produksi, untuk Produk Makanan Minuman Tertentu yang dapat Diproduksi oleh Industri Rumah Tangga'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '2', 'program_kode' => '4', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Penerbitan Sertifikat Laik Higiene Sanitasi Tempat Pengelolaan Makanan (TPM) antara lain Jasa Boga, Rumah Makan/Restoran dan Depot Air Minum (DAM)'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '2', 'program_kode' => '4', 'kegiatan_kode' => '205', 'kegiatan_nama' => 'Penerbitan Stiker Pembinaan pada Makanan Jajanan dan Sentra Makanan Jajanan'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '2', 'program_kode' => '4', 'kegiatan_kode' => '206', 'kegiatan_nama' => 'Pemeriksaan dan Tindak Lanjut Hasil Pemeriksaan Post Market pada Produksi dan Produk Makanan Minuman Industri Rumah Tangga'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '2', 'program_kode' => '5', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Advokasi, Pemberdayaan, Kemitraan, Peningkatan Peran serta Masyarakat dan Lintas Sektor Tingkat Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '2', 'program_kode' => '5', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pelaksanaan Sehat dalam rangka Promotif Preventif Tingkat Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '2', 'program_kode' => '5', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pengembangan dan Pelaksanaan Upaya Kesehatan Bersumber Daya Masyarakat (UKBM) Tingkat Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '3', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengelolaan SDA dan Bangunan Pengaman Pantai pada Wilayah Sungai (WS) dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '3', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pengembangan dan Pengelolaan Sistem Irigasi Primer dan Sekunder pada Daerah Irigasi yang Luasnya dibawah 1000 Ha dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '3', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengelolaan dan Pengembangan Sistem Penyediaan Air Minum (SPAM) di Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '3', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengembangan Sistem dan Pengelolaan Persampahan di Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '3', 'program_kode' => '5', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengelolaan dan Pengembangan Sistem Air Limbah Domestik dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '3', 'program_kode' => '6', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengelolaan dan Pengembangan Sistem Drainase yang Terhubung Langsung dengan Sungai dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '3', 'program_kode' => '7', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyelenggaraan Infrastruktur pada Permukiman di Kawasan Strategis Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '3', 'program_kode' => '8', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyelenggaraan Bangunan Gedung di Wilayah Daerah Kabupaten/Kota, Pemberian Izin Mendirikan Bangunan (IMB) dan Sertifikat Laik Fungsi Bangunan Gedung'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '3', 'program_kode' => '9', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyelenggaraan Penataan Bangunan dan Lingkungannya di Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '3', 'program_kode' => '10', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyelenggaraan Jalan Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '3', 'program_kode' => '11', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyelenggaraan Pelatihan Tenaga Terampil Konstruksi'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '3', 'program_kode' => '11', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penyelenggaraan Sistem Informasi Jasa Konstruksi Cakupan Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '3', 'program_kode' => '11', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Penerbitan Izin Usaha Jasa Konstruksi Nasional (Non Kecil dan Kecil)'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '3', 'program_kode' => '11', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Pengawasan Tertib Usaha, Tertib Penyelenggaraan dan Tertib Pemanfaatan Jasa Konstruksi'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '3', 'program_kode' => '12', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penetapan Rencana Tata Ruang Wilayah (RTRW) dan Rencana Rinci Tata Ruang (RRTR) Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '3', 'program_kode' => '12', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Koordinasi dan Sinkronisasi Perencanaan Tata Ruang Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '3', 'program_kode' => '12', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Koordinasi dan Sinkronisasi Pemanfaatan Ruang Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '3', 'program_kode' => '12', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Koordinasi dan Sinkronisasi Pengendalian Pemanfaatan Ruang Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '4', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pendataan Penyediaan dan Rehabilitasi Rumah Korban Bencana atau Relokasi Program Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '4', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Sosialisasi dan Persiapan Penyediaan dan Rehabilitasi Rumah Korban Bencana atau Relokasi Program Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '4', 'program_kode' => '2', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pembangunan dan Rehabilitasi Rumah Korban Bencana atau Relokasi Program Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '4', 'program_kode' => '2', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Pendistribusian dan Serah Terima Rumah bagi Korban Bencana atau Relokasi Program Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '4', 'program_kode' => '2', 'kegiatan_kode' => '205', 'kegiatan_nama' => 'Pembinaan Pengelolaan Rumah Susun Umum dan/atau Rumah Khusus'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '4', 'program_kode' => '2', 'kegiatan_kode' => '206', 'kegiatan_nama' => 'Penerbitan Izin Pembangunan dan Pengembangan Perumahan'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '4', 'program_kode' => '2', 'kegiatan_kode' => '207', 'kegiatan_nama' => 'Penerbitan Sertifikat Kepemilikan Bangunan Gedung (SKGB)'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '4', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penerbitan Izin Pembangunan dan Pengembangan Kawasan Permukiman'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '4', 'program_kode' => '3', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penataan dan Peningkatan Kualitas Kawasan Permukiman Kumuh dengan Luas di Bawah 10 (sepuluh) Ha'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '4', 'program_kode' => '3', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Peningkatan Kualitas Kawasan Permukiman Kumuh dengan Luas di Bawah 10 (sepuluh) Ha'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '4', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pencegahan Perumahan dan Kawasan Permukiman Kumuh pada Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '4', 'program_kode' => '5', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Urusan Penyelenggaraan PSU Perumahan'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '4', 'program_kode' => '6', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Sertifikasi dan Registrasi bagi Orang atau Badan Hukum yang Melaksanakan Perancangan dan Perencanaan Rumah serta Perencanaan Prasarana, Sarana dan Utilitas Umum PSU Tingkat Kemampuan Kecil'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '5', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penanganan Gangguan Ketenteraman dan Ketertiban Umum dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '5', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penegakan Peraturan Daerah Kabupaten/Kota dan Peraturan Bupati/Wali Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '5', 'program_kode' => '2', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pembinaan Penyidik Pegawai Negeri Sipil (PPNS) Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '5', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pelayanan Informasi Rawan Bencana Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '5', 'program_kode' => '3', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pelayanan Pencegahan dan Kesiapsiagaan Terhadap Bencana'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '5', 'program_kode' => '3', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pelayanan Penyelamatan dan Evakuasi Korban Bencana'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '5', 'program_kode' => '3', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Penataan Sistem Dasar Penanggulangan Bencana'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '5', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pencegahan, Pengendalian, Pemadaman, Penyelamatan, dan Penanganan Bahan Berbahaya dan Beracun Kebakaran dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '5', 'program_kode' => '4', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Inspeksi Peralatan Proteksi Kebakaran'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '5', 'program_kode' => '4', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Investigasi Kejadian Kebakaran'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '5', 'program_kode' => '4', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Pemberdayaan Masyarakat dalam Pencegahan Kebakaran'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '5', 'program_kode' => '4', 'kegiatan_kode' => '205', 'kegiatan_nama' => 'Penyelenggaraan Operasi Pencarian dan Pertolongan terhadap Kondisi Membahayakan Manusia'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '6', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pemberdayaan Sosial Komunitas Adat Terpencil (KAT)'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '6', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pengumpulan Sumbangan dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '6', 'program_kode' => '2', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pengembangan Potensi Sumber Kesejahteraan Sosial Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '6', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pemulangan Warga Negara Migran Korban Tindak Kekerasan dari Titik Debarkasi di Daerah Kabupaten/Kota untuk dipulangkan ke Desa/Kelurahan Asal'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '6', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Rehabilitasi Sosial Dasar Penyandang Disabilitas Terlantar, Anak Terlantar, Lanjut Usia Terlantar, serta Gelandangan Pengemis di Luar Panti Sosial'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '6', 'program_kode' => '4', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Rehabilitasi Sosial Penyandang Masalah Kesejahteraan Sosial (PMKS) Lainnya Bukan Korban HIV/AIDS dan NAPZA di Luar Panti Sosial'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '6', 'program_kode' => '5', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pemeliharaan Anak-Anak Terlantar'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '6', 'program_kode' => '5', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pengelolaan Data Fakir Miskin Cakupan Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '6', 'program_kode' => '6', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Perlindungan Sosial Korban Bencana Alam dan Sosial Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '6', 'program_kode' => '6', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penyelenggaraan Pemberdayaan Masyarakat terhadap Kesiapsiagaan Bencana Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '1', 'bidang_kode' => '6', 'program_kode' => '7', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pemeliharaan Taman Makam Pahlawan Nasional Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '7', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyusunan Rencana Tenaga Kerja (RTK)'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '7', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pelaksanaan Pelatihan berdasarkan Unit Kompetensi'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '7', 'program_kode' => '3', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pembinaan Lembaga Pelatihan Kerja Swasta'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '7', 'program_kode' => '3', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Perizinan dan Pendaftaran Lembaga Pelatihan Kerja'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '7', 'program_kode' => '3', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Konsultansi Produktivitas pada Perusahaan Kecil'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '7', 'program_kode' => '3', 'kegiatan_kode' => '205', 'kegiatan_nama' => 'Pengukuran Produktivitas Tingkat Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '7', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pelayanan Antarkerja di Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '7', 'program_kode' => '4', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penerbitan Izin Lembaga Penempatan Tenaga Kerja Swasta (LPTKS) dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '7', 'program_kode' => '4', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pengelolaan Informasi Pasar Kerja'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '7', 'program_kode' => '4', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Pelindungan PMI (Pra dan Purna Penempatan) di Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '7', 'program_kode' => '4', 'kegiatan_kode' => '205', 'kegiatan_nama' => 'Penerbitan Perpanjangan IMTA yang Lokasi Kerja dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '7', 'program_kode' => '5', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengesahan Peraturan Perusahaan dan Pendaftaran Perjanjian Kerja Bersama untuk Perusahaan yang hanya Beroperasi dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '7', 'program_kode' => '5', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pencegahan dan Penyelesaian Perselisihan Hubungan Industrial, Mogok Kerja dan Penutupan Perusahaan di Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '8', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pelembagaan Pengarusutamaan Gender (PUG) pada Lembaga Pemerintah Kewenangan Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '8', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pemberdayaan Perempuan Bidang Politik, Hukum, Sosial, dan Ekonomi pada Organisasi Kemasyarakatan Kewenangan Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '8', 'program_kode' => '2', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Penguatan dan Pengembangan Lembaga Penyedia Layanan Pemberdayaan Perempuan Kewenangan Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '8', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pencegahan Kekerasan terhadap Perempuan Lingkup Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '8', 'program_kode' => '3', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penyediaan Layanan Rujukan Lanjutan bagi Perempuan Korban Kekerasan yang Memerlukan Koordinasi Kewenangan Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '8', 'program_kode' => '3', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Penguatan dan Pengembangan Lembaga Penyedia Layanan Perlindungan Perempuan Tingkat Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '8', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Peningkatan Kualitas Keluarga dalam Mewujudkan Kesetaraan Gender (KG) dan Hak Anak Tingkat Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '8', 'program_kode' => '4', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penguatan dan Pengembangan Lembaga Penyedia Layanan Peningkatan Kualitas Keluarga dalam Mewujudkan KG dan Hak Anak yang Wilayah Kerjanya dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '8', 'program_kode' => '4', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Penyediaan Layanan bagi Keluarga dalam Mewujudkan KG dan Hak Anak yang Wilayah Kerjanya dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '8', 'program_kode' => '5', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengumpulan, Pengolahan Analisis dan Penyajian Data Gender dan Anak Dalam Kelembagaan Data di Tingkat Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '8', 'program_kode' => '6', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pelembagaan PHA pada Lembaga Pemerintah, Nonpemerintah, dan Dunia Usaha Kewenangan Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '8', 'program_kode' => '6', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penguatan dan Pengembangan Lembaga Penyedia Layanan Peningkatan Kualitas Hidup Anak Kewenangan Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '8', 'program_kode' => '7', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pencegahan Kekerasan Terhadap Anak yang Melibatkan para Pihak Lingkup Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '8', 'program_kode' => '7', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penyediaan Layanan bagi Anak yang Memerlukan Perlindungan Khusus yang Memerlukan Koordinasi Tingkat Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '8', 'program_kode' => '7', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Penguatan dan Pengembangan Lembaga Penyedia Layanan bagi Anak yang Memerlukan Perlindungan Khusus Tingkat Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '9', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyediaan Infrastruktur dan Seluruh Pendukung Kemandirian Pangan sesuai Kewenangan Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '9', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyediaan dan Penyaluran Pangan Pokok atau Pangan Lainnya sesuai dengan Kebutuhan Daerah Kabupaten/Kota dalam rangka Stabilisasi Pasokan dan Harga Pangan'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '9', 'program_kode' => '3', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pengelolaan dan Keseimbangan Cadangan Pangan Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '9', 'program_kode' => '3', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Penentuan Harga Minimum Daerah untuk Pangan Lokal yang Tidak Ditetapkan oleh Pemerintah Pusat dan Pemerintah Provinsi'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '9', 'program_kode' => '3', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Pelaksanaan Pencapaian Target Konsumsi Pangan Perkapita/Tahun sesuai dengan Angka Kecukupan Gizi'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '9', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyusunan Peta Kerentanan dan Ketahanan Pangan Kecamatan'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '9', 'program_kode' => '4', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penanganan Kerawanan Pangan Kewenangan Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '9', 'program_kode' => '5', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pelaksanaan Pengawasan Keamanan Pangan Segar Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '10', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pemberian Izin Lokasi Dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '10', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyelesaian Sengketa Tanah Garapan dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '10', 'program_kode' => '5', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyelesaian Masalah Ganti Kerugian dan Santunan Tanah untuk Pembangunan oleh Pemerintah Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '10', 'program_kode' => '6', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penetapan Subjek dan Objek Redistribusi Tanah serta Ganti Kerugian Tanah Kelebihan Maksimum dan Tanah Absentee dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '10', 'program_kode' => '6', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penetapan Ganti Kerugian Tanah Kelebihan Maksimum dan Tanah Absentee Lintas Daerah Kabupaten/Kota dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '10', 'program_kode' => '7', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penetapan Tanah Ulayat yang Lokasinya dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '10', 'program_kode' => '8', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyelesaian Masalah Tanah Kosong'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '10', 'program_kode' => '8', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Inventarisasi dan Pemanfaatan Tanah Kosong'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '10', 'program_kode' => '9', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penerbitan Izin Membuka Tanah'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '10', 'program_kode' => '10', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penggunaan Tanah yang Hamparannya dalam satu Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '11', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Rencana Perlindungan dan Pengelolaan Lingkungan Hidup (RPPLH) Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '11', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penyelenggaraan Kajian Lingkungan Hidup Strategis (KLHS) Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '11', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pencegahan Pencemaran dan/atau Kerusakan Lingkungan Hidup Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '11', 'program_kode' => '3', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penanggulangan Pencemaran dan/atau Kerusakan Lingkungan Hidup Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '11', 'program_kode' => '3', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pemulihan Pencemaran dan/atau Kerusakan Lingkungan Hidup Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '11', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengelolaan Keanekaragaman Hayati Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '11', 'program_kode' => '5', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyimpanan Sementara Limbah B3'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '11', 'program_kode' => '5', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pengumpulan Limbah B3 dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '11', 'program_kode' => '6', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pembinaan dan Pengawasan Terhadap Usaha dan/atau Kegiatan yang Izin Lingkungan dan Izin PPLH diterbitkan oleh Pemerintah Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '11', 'program_kode' => '7', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengakuan MHA, Kearifan Lokal, Pengetahuan Tradisional, dan Hak MHA yang terkait dengan PPLH'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '11', 'program_kode' => '7', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Peningkatan Kapasitas MHA dan Kearifan Lokal, Pengetahuan Tradisional dan Hak MHA yang terkait dengan PPLH'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '11', 'program_kode' => '8', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyelenggaraan Pendidikan, Pelatihan, dan Penyuluhan Lingkungan Hidup untuk Lembaga Kemasyarakatan Tingkat Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '11', 'program_kode' => '9', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pemberian Penghargaan Lingkungan Hidup Tingkat Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '11', 'program_kode' => '10', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyelesaian Pengaduan Masyarakat di Bidang Perlindungan dan Pengelolaan Lingkungan Hidup (PPLH) Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '11', 'program_kode' => '11', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengelolaan Sampah'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '11', 'program_kode' => '11', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penerbitan Izin Pendaurulangan Sampah/Pengelolaan Sampah, Pengangkutan Sampah dan Pemrosesan Akhir Sampah yang Diselenggarakan oleh Swasta'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '11', 'program_kode' => '11', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pembinaan dan Pengawasan Pengelolaan Sampah yang Diselenggarakan oleh Pihak Swasta'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '12', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pelayanan Pendaftaran Penduduk'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '12', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penataan Pendaftaran Penduduk'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '12', 'program_kode' => '2', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Penyelenggaraan Pendaftaran Penduduk'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '12', 'program_kode' => '2', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Pembinaan dan Pengawasan Penyelenggaraan Pendaftaran Penduduk'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '12', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pelayanan Pencatatan Sipil'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '12', 'program_kode' => '3', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penyelenggaraan Pencatatan Sipil'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '12', 'program_kode' => '3', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pembinaan dan Pengawasan Penyelenggaraan Pencatatan Sipil'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '12', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengumpulan Data Kependudukan dan Pemanfaatan dan Penyajian Database Kependudukan'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '12', 'program_kode' => '4', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penataan Pengelolaan Informasi Administrasi Kependudukan'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '12', 'program_kode' => '4', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Penyelenggaraan Pengelolaan Informasi Administrasi Kependudukan'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '12', 'program_kode' => '4', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Pembinaan dan Pengawasan Pengelolaan Informasi Administrasi Kependudukan'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '12', 'program_kode' => '5', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyusunan Profil Kependudukan'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '13', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyelenggaraan Penataan Desa'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '13', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Fasilitasi Kerja sama antar Desa'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '13', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pembinaan dan Pengawasan Penyelenggaraan Administrasi Pemerintahan Desa'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '13', 'program_kode' => '5', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pemberdayaan Lembaga Kemasyarakatan yang Bergerak di Bidang Pemberdayaan Desa dan Lembaga Adat Tingkat Daerah Kabupaten/Kota serta Pemberdayaan Masyarakat Hukum Adat yang Masyarakat Pelakunya Hukum Adat yang Sama dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '14', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pemaduan dan Sinkronisasi Kebijakan Pemerintah Daerah Provinsi dengan Pemerintah Daerah Kabupaten/Kota dalam rangka Pengendalian Kuantitas Penduduk'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '14', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pemetaan Perkiraan Pengendalian Penduduk Cakupan Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '14', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pelaksanaan Advokasi, Komunikasi, Informasi dan Edukasi (KIE) Pengendalian Penduduk dan KB sesuai Kearifan Budaya Lokal'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '14', 'program_kode' => '3', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pendayagunaan Tenaga Penyuluh KB/Petugas Lapangan KB (PKB/PLKB)'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '14', 'program_kode' => '3', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pengendalian dan Pendistribusian Kebutuhan Alat dan Obat Kontrasepsi serta Pelaksanaan Pelayanan KB di Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '14', 'program_kode' => '3', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Pemberdayaan dan Peningkatan Peran serta Organisasi Kemasyarakatan Tingkat Daerah Kabupaten/Kota dalam Pelaksanaan Pelayanan dan Pembinaan Kesertaan Ber-KB'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '14', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pelaksanaan Pembangunan Keluarga melalui Pembinaan Ketahanan dan Kesejahteraan Keluarga'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '14', 'program_kode' => '4', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pelaksanaan dan Peningkatan Peran Serta Organisasi Kemasyarakatan Tingkat Daerah Kabupaten/ Kota dalam Pembangunan Keluarga Melalui Pembinaan Ketahanan dan Kesejahteraan Keluarga'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penetapan Rencana Induk Jaringan LLAJ Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penyediaan Perlengkapan Jalan di Jalan Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '2', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pengelolaan Terminal Penumpang Tipe C'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '2', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Penerbitan Izin Penyelenggaraan dan Pembangunan Fasilitas Parkir'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '2', 'kegiatan_kode' => '205', 'kegiatan_nama' => 'Pengujian Berkala Kendaraan Bermotor'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '2', 'kegiatan_kode' => '206', 'kegiatan_nama' => 'Pelaksanaan Manajemen dan Rekayasa Lalu Lintas untuk Jaringan Jalan Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '2', 'kegiatan_kode' => '207', 'kegiatan_nama' => 'Persetujuan Hasil Analisis Dampak Lalu Lintas (Andalalin) untuk Jalan Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '2', 'kegiatan_kode' => '208', 'kegiatan_nama' => 'Audit dan Inspeksi Keselamatan LLAJ di Jalan'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '2', 'kegiatan_kode' => '209', 'kegiatan_nama' => 'Penyediaan Angkutan Umum untuk Jasa Angkutan Orang dan/atau Barang antar Kota dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '2', 'kegiatan_kode' => '210', 'kegiatan_nama' => 'Penetapan Kawasan Perkotaan untuk Pelayanan Angkutan Perkotaan yang Melampaui Batas 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '2', 'kegiatan_kode' => '211', 'kegiatan_nama' => 'Penetapan Rencana Umum Jaringan Trayek Perkotaan dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '2', 'kegiatan_kode' => '212', 'kegiatan_nama' => 'Penetapan Rencana Umum Jaringan Trayek Pedesaan dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '2', 'kegiatan_kode' => '213', 'kegiatan_nama' => 'Penetapan Wilayah Operasi Angkutan Orang dengan Menggunakan Taksi dalam Kawasan Perkotaan yang Wilayah Operasinya dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '2', 'kegiatan_kode' => '214', 'kegiatan_nama' => 'Penerbitan Izin Penyelenggaraan Angkutan Orang dalam Trayek Lintas Daerah Kabupaten/Kota dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '2', 'kegiatan_kode' => '215', 'kegiatan_nama' => 'Penerbitan Izin Penyelenggaraan Angkutan Taksi yang Wilayah Operasinya dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '2', 'kegiatan_kode' => '216', 'kegiatan_nama' => 'Penetapan Tarif Kelas Ekonomi untuk Angkutan Orang yang Melayani Trayek serta Angkutan Perkotaan dan Perdesaan dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penerbitan Izin Usaha Angkutan Laut bagi Badan Usaha yang Berdomisili dalam Daerah Kabupaten/Kota dan Beroperasi pada Lintas Pelabuhan di Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '3', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penerbitan Izin Usaha Angkutan Laut Pelayaran Rakyat bagi Orang Perorangan atau Badan Usaha yang Berdomisili dan yang Beroperasi pada Lintas Pelabuhan dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '3', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Penerbitan Izin Usaha Penyelenggaraan Angkutan Sungai dan Danau sesuai dengan Domisili Orang Perseorangan Warga Negara Indonesia atau Badan Usaha'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '3', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Pembangunan dan Penerbitan Izin Pelabuhan Sungai dan Danau yang Melayani Trayek dalam 1 Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '3', 'kegiatan_kode' => '205', 'kegiatan_nama' => 'Penerbitan Izin Usaha Penyelenggaraan Angkutan Penyeberangan sesuai dengan Domisili Badan Usaha'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '3', 'kegiatan_kode' => '206', 'kegiatan_nama' => 'Penetapan Lintas Penyeberangan dan Persetujuan Pengoperasian Kapal dalam Daerah Kabupaten/Kota yang Terletak pada Jaringan Jalan Kabupaten/Kota dan/atau Jaringan Jalur Kereta Api Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '3', 'kegiatan_kode' => '207', 'kegiatan_nama' => 'Penetapan Lintas Penyeberangan dan Persetujuan Pengoperasian untuk Kapal yang Melayani Penyeberangan dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '3', 'kegiatan_kode' => '208', 'kegiatan_nama' => 'Penerbitan Izin Usaha Jasa terkait dengan Perawatan dan Perbaikan Kapal'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '3', 'kegiatan_kode' => '209', 'kegiatan_nama' => 'Penetapan Tarif Angkutan Penyeberangan Penumpang Kelas Ekonomi dan Kendaraan beserta Muatannya pada Lintas Penyeberangan dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '3', 'kegiatan_kode' => '210', 'kegiatan_nama' => 'Penetapan Rencana Induk dan Daerah Lingkungan Kerja (DLKR)/Daerah Lingkungan Kepentingan (DLKP) Pelabuhan Pengumpan Lokal'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '3', 'kegiatan_kode' => '211', 'kegiatan_nama' => 'Penetapan Rencana Induk dan DLKR/DLKP untuk Pelabuhan Sungai dan Danau'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '3', 'kegiatan_kode' => '212', 'kegiatan_nama' => 'Pembangunan, Penerbitan Izin Pembangunan dan Pengoperasian Pelabuhan Pengumpan Lokal'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '3', 'kegiatan_kode' => '213', 'kegiatan_nama' => 'Pembangunan dan Penerbitan Izin Pembangunan dan Pengoperasian Pelabuhan Sungai dan Danau'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '3', 'kegiatan_kode' => '214', 'kegiatan_nama' => 'Penerbitan Izin Usaha untuk Badan Usaha Pelabuhan di Pelabuhan Pengumpan Lokal'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '3', 'kegiatan_kode' => '215', 'kegiatan_nama' => 'Penerbitan Izin Pengembangan Pelabuhan untuk Pelabuhan Pengumpan Lokal'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '3', 'kegiatan_kode' => '216', 'kegiatan_nama' => 'Penerbitan Izin Pengoperasian Pelabuhan Selama 24 Jam untuk Pelabuhan Pengumpan Lokal'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '3', 'kegiatan_kode' => '217', 'kegiatan_nama' => 'Penerbitan Izin Pekerjaan Pengerukan di Wilayah Perairan Pelabuhan Pengumpan Lokal'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '3', 'kegiatan_kode' => '218', 'kegiatan_nama' => 'Penerbitan Izin Reklamasi di Wilayah Perairan Pelabuhan Pengumpan Lokal'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '3', 'kegiatan_kode' => '219', 'kegiatan_nama' => 'Penerbitan Izin Pengelolaan Terminal untuk Kepentingan Sendiri (TUKS) di dalam DLKR/DLKP Pelabuhan Pengumpan Lokal'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penerbitan Izin Mendirikan Bangunan Tempat Pendaratan dan Lepas Landas Helikopter'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '5', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penetapan Rencana Induk Perkeretaapian'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '5', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penerbitan Izin Usaha, Izin Pembangunan dan Izin Operasi Prasarana Perkeretaapian Umum yang Jaringan Jalurnya dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '5', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Penetapan Jaringan Jalur Kereta Api yang Jaringannya dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '5', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Penetapan Kelas Stasiun untuk Stasiun pada Jaringan Jalur Kereta Api Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '5', 'kegiatan_kode' => '205', 'kegiatan_nama' => 'Penerbitan Izin Operasi Sarana Perkeretaapian Umum yang Jaringan Jalurnya Melintasi Batas dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '5', 'kegiatan_kode' => '206', 'kegiatan_nama' => 'Penetapan Jaringan Pelayanan Perkeretaapian pada Jaringan Jalur Perkeretaapian Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '15', 'program_kode' => '5', 'kegiatan_kode' => '207', 'kegiatan_nama' => 'Penerbitan Izin Pengadaan atau Pembangunan Perkeretapian Khusus, Izin Operasi, dan Penetapan Jalur Kereta Api Khusus yang Jaringannya dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '16', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengelolaan Informasi dan Komunikasi Publik Pemerintah Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '16', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengelolaan Nama Domain yang telah Ditetapkan oleh Pemerintah Pusat dan Sub Domain di Lingkup Pemerintah Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '16', 'program_kode' => '3', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pengelolaan e-government Di Lingkup Pemerintah Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '17', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penerbitan Izin Usaha Simpan Pinjam untuk Koperasi dengan Wilayah Keanggotaan dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '17', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penerbitan Izin Pembukaan Kantor Cabang, Cabang Pembantu dan Kantor Kas Koperasi Simpan Pinjam untuk Koperasi dengan Wilayah Keanggotaan dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '17', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pemeriksaan dan Pengawasan Koperasi, Koperasi Simpan Pinjam/Unit Simpan Pinjam Koperasi yang Wilayah Keanggotaannya dalam Daerah Kabupaten/ Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '17', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penilaian Kesehatan Koperasi Simpan Pinjam/Unit Simpan Pinjam Koperasi yang Wilayah Keanggotaanya dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '17', 'program_kode' => '5', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pendidikan dan Latihan Perkoperasian Bagi Koperasi yang Wilayah Keanggotaan dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '17', 'program_kode' => '5', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pendidikan dan Latihan UKM Bagi UKM dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '17', 'program_kode' => '5', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pendidikan dan Pelatihan SDM Usaha Mikro dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '17', 'program_kode' => '6', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pemberdayaan dan Perlindungan Koperasi yang Keanggotaannya dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '17', 'program_kode' => '7', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pemberdayaan Usaha Mikro yang Dilakukan melalui Pendataan, Kemitraan, Kemudahan Perizinan, Penguatan Kelembagaan dan Koordinasi dengan Para Pemangku Kepentingan'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '17', 'program_kode' => '8', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengembangan Usaha Mikro dengan Orientasi Peningkatan Skala Usaha Menjadi Usaha Kecil'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '18', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penetapan Pemberian Fasilitas/Insentif Dibidang Penanaman Modal yang menjadi Kewenangan Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '18', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pembuatan Peta Potensi Investasi Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '18', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyelenggaraan Promosi Penanaman Modal yang menjadi Kewenangan Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '18', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pelayanan Perizinan dan Non Perizinan secara Terpadu Satu Pintu dibidang Penanaman Modal yang menjadi Kewenangan Daerah Kabupaten/ Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '18', 'program_kode' => '5', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengendalian Pelaksanaan Penanaman Modal yang menjadi Kewenangan Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '18', 'program_kode' => '6', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengelolaan Data dan Informasi Perizinan dan Non Perizinan yang Terintegrasi pada Tingkat Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '19', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyadaran, Pemberdayaan, dan Pengembangan Pemuda dan Kepemudaan Terhadap Pemuda Pelopor Kabupaten/Kota, Wirausaha Muda Pemula, dan Pemuda Kader Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '19', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pemberdayaan dan Pengembangan Organisasi Kepemudaan Tingkat Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '19', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pembinaan dan Pengembangan Olahraga Pendidikan pada Jenjang Pendidikan yang menjadi Kewenangan Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '19', 'program_kode' => '3', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penyelenggaraan Kejuaraan Olahraga Tingkat Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '19', 'program_kode' => '3', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pembinaan dan Pengembangan Olahraga Prestasi Tingkat Daerah Provinsi'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '19', 'program_kode' => '3', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Pembinaan dan Pengembangan Organisasi Olahraga'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '19', 'program_kode' => '3', 'kegiatan_kode' => '205', 'kegiatan_nama' => 'Pembinaan dan Pengembangan Olahraga Rekreasi'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '19', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pembinaan dan Pengembangan Organisasi Kepramukaan'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '20', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyelenggaraan Statistik Sektoral di Lingkup Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '21', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyelenggaraan Persandian untuk Pengamanan Informasi Pemerintah Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '21', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penetapan Pola Hubungan Komunikasi Sandi Antar Perangkat Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '22', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengelolaan Kebudayaan yang Masyarakat Pelakunya dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '22', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pelestarian Kesenian Tradisional yang Masyarakat Pelakunya dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '22', 'program_kode' => '2', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pembinaan Lembaga Adat yang Penganutnya dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '22', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pembinaan Kesenian yang Masyarakat Pelakunya dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '22', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pembinaan Sejarah Lokal dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '22', 'program_kode' => '5', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penetapan Cagar Budaya Peringkat Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '22', 'program_kode' => '5', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pengelolaan Cagar Budaya Peringkat Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '22', 'program_kode' => '5', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Penerbitan Izin membawa Cagar Budaya ke Luar Daerah Kabupaten/Kota dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '22', 'program_kode' => '6', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengelolaan Museum Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '23', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengelolaan Perpustakaan Tingkat Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '23', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pembudayaan Gemar Membaca Tingkat Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '23', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pelestarian Naskah Kuno Milik Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '23', 'program_kode' => '3', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pengembangan Koleksi Budaya Etnis Nusantara yang ditemukan oleh Pemerintah Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '24', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengelolaan Arsip Dinamis Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '24', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pengelolaan Arsip Statis Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '24', 'program_kode' => '2', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pengelolaan Simpul Jaringan Informasi Kearsipan Nasional Tingkat Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '24', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pemusnahan Arsip Dilingkungan Pemerintah Daerah Kabupaten/Kota yang Memiliki Retensi di Bawah 10 (sepuluh) Tahun'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '24', 'program_kode' => '3', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Perlindungan dan Penyelamatan Arsip Akibat Bencana yang Berskala Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '24', 'program_kode' => '3', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Penyelamatan Arsip Perangkat Daerah Kabupaten/Kota yang Digabung dan/atau Dibubarkan, dan Pemekaran Daerah Kecamatan dan Desa/Kelurahan'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '24', 'program_kode' => '3', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Autentikasi Arsip Statis dan Arsip Hasil Alih Media Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '24', 'program_kode' => '3', 'kegiatan_kode' => '205', 'kegiatan_nama' => 'Pencarian Arsip Statis Kabupaten/Kota yang Dinyatakan Hilang'],
['permen_ver' => 1, 'urusan_kode' => '2', 'bidang_kode' => '24', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pelayanan Izin Penggunaan Arsip yang Bersifat Tertutup di Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '25', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengelolaan Penangkapan Ikan di Wilayah Sungai, Danau, Waduk, Rawa, dan Genangan Air Lainnya yang dapat Diusahakan dalam 1 (satu) Daerah Kabupaten/ Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '25', 'program_kode' => '3', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pemberdayaan Nelayan Kecil dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '25', 'program_kode' => '3', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pengelolaan dan Penyelenggaraan Tempat Pelelangan Ikan (TPI)'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '25', 'program_kode' => '3', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Penerbitan Tanda Daftar Kapal Perikanan Berukuran sampai dengan 10 GT di Wilayah Sungai, Danau, Waduk, Rawa, dan Genangan Air Lainnya yang dapat Diusahakan dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '25', 'program_kode' => '3', 'kegiatan_kode' => '205', 'kegiatan_nama' => 'Penerbitan Izin Pengadaan Kapal Penangkap Ikan dan Kapal Pengangkut Ikan dengan Ukuran sampai dengan 10 GT di Wilayah Sungai, Danau, Waduk, Rawa, dan Genangan Air Lainnya yang dapat Diusahakan dalam 1 (satu) Daerah Kabupaten/ Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '25', 'program_kode' => '3', 'kegiatan_kode' => '206', 'kegiatan_nama' => 'Pendaftaran Kapal Perikanan Berukuran Sampai Dengan 10 GT yang Beroperasi di Sungai, Danau, Waduk, Rawa, dan Genangan Air Lainnya yang dapat Diusahakan dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '25', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penerbitan Izin Usaha Perikanan di Bidang Pembudidayaan Ikan yang Usahanya dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '25', 'program_kode' => '4', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pemberdayaan Pembudi Daya Ikan Kecil'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '25', 'program_kode' => '4', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Penerbitan Tanda Daftar bagi Pembudi Daya Ikan Kecil (TDPIK) dalam 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '25', 'program_kode' => '4', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Pengelolaan Pembudidayaan Ikan'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '25', 'program_kode' => '5', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengawasan Sumber Daya Perikanan di Wilayah Sungai, Danau, Waduk, Rawa, dan Genangan Air Lainnya yang dapat Diusahakan Dalam Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '25', 'program_kode' => '6', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penerbitan Tanda Daftar Usaha Pengolahan Hasil Perikanan Bagi Usaha Skala Mikro dan Kecil'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '25', 'program_kode' => '6', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pembinaan Mutu dan Keamanan Hasil Perikanan Bagi Usaha Pengolahan dan Pemasaran Skala Mikro dan Kecil'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '25', 'program_kode' => '6', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Penyediaan dan Penyaluran Bahan Baku Industri Pengolahan Ikan dalam 1 (satu) Daerah Kabupaten/ Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '26', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengelolaan Daya Tarik Wisata Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '26', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pengelolaan Kawasan Strategis Pariwisata Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '26', 'program_kode' => '2', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pengelolaan Destinasi Pariwisata Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '26', 'program_kode' => '2', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Penetapan Tanda Daftar Usaha Pariwisata Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '26', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pemasaran Pariwisata Dalam dan Luar Negeri Daya Tarik, Destinasi dan Kawasan Strategis Pariwisata Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '26', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyediaan Prasarana (Zona Kreatif/Ruang Kreatif/Kota Kreatif) sebagai Ruang Berekspresi, Berpromosi dan Berinteraksi bagi Insan Kreatif di Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '26', 'program_kode' => '4', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pengembangan Ekosistem Ekonomi Kreatif '],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '26', 'program_kode' => '5', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pelaksanaan Peningkatan Kapasitas Sumber Daya Manusia Pariwisata dan Ekonomi Kreatif Tingkat Dasar'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '26', 'program_kode' => '5', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pengembangan Kapasitas Pelaku Ekonomi Kreatif'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '27', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengawasan Penggunaan Sarana Pertanian'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '27', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pengelolaan Sumber Daya Genetik (SDG) Hewan, Tumbuhan, dan Mikro Organisme Kewenangan Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '27', 'program_kode' => '2', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Peningkatan Mutu dan Peredaran Benih/Bibit Ternak dan Tanaman Pakan Ternak serta Pakan dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '27', 'program_kode' => '2', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Pengawasan Obat Hewan di Tingkat Pengecer'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '27', 'program_kode' => '2', 'kegiatan_kode' => '205', 'kegiatan_nama' => 'Pengendalian dan Pengawasan Penyediaan dan Peredaran Benih/Bibit Ternak, dan Hijauan Pakan Ternak dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '27', 'program_kode' => '2', 'kegiatan_kode' => '206', 'kegiatan_nama' => 'Penyediaan Benih/Bibit Ternak dan Hijauan Pakan Ternak yang Sumbernya dalam 1 (satu) Daerah Kabupaten/Kota Lain'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '27', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengembangan Prasarana Pertanian'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '27', 'program_kode' => '3', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pembangunan Prasarana Pertanian'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '27', 'program_kode' => '3', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pengelolaan Wilayah Sumber Bibit Ternak dan Rumpun/Galur Ternak dalam Daerah Kabupaten/ Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '27', 'program_kode' => '3', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Pengembangan Lahan Penggembalaan Umum'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '27', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penjaminan Kesehatan Hewan, Penutupan dan Pembukaan Daerah Wabah Penyakit Hewan Menular Dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '27', 'program_kode' => '4', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pengawasan Pemasukan dan Pengeluaran Hewan dan Produk Hewan Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '27', 'program_kode' => '4', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pengelolaan Pelayanan Jasa Laboratorium dan Jasa Medik Veteriner dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '27', 'program_kode' => '4', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Penerapan dan Pengawasan Persyaratan Teknis Kesehatan Masyarakat Veteriner'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '27', 'program_kode' => '4', 'kegiatan_kode' => '205', 'kegiatan_nama' => 'Penerapan dan Pengawasan Persyaratan Teknis Kesejahteraan Hewan'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '27', 'program_kode' => '5', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengendalian dan Penanggulangan Bencana Pertanian Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '27', 'program_kode' => '6', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penerbitan Izin Usaha Pertanian yang Kegiatan Usahanya dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '27', 'program_kode' => '6', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penerbitan Izin Usaha Produksi Benih/Bibit Ternak dan Pakan, Fasilitas Pemeliharaan Hewan, Rumah Sakit Hewan/Pasar Hewan, Rumah Potong Hewan'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '27', 'program_kode' => '6', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Izin Usaha Pengecer (Toko, Retail, Sub Distributor) Obat Hewan'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '27', 'program_kode' => '7', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pelaksanaan Penyuluhan Pertanian'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '28', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengelolaan Taman Hutan Raya (TAHURA) Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '29', 'program_kode' => '5', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penatausahaan Izin Pemanfaatan Langsung Panas Bumi dalam Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '30', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penerbitan Izin Pengelolaan Pasar Rakyat, Pusat Perbelanjaan, dan Izin Usaha Toko Swalayan'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '30', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penerbitan Tanda Daftar Gudang'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '30', 'program_kode' => '2', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Penerbitan Surat Tanda Pendaftaran Waralaba (STPW) untuk Penerima Waralaba dari Waralaba Dalam Negeri'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '30', 'program_kode' => '2', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Penerbitan Surat Tanda Pendaftaran Waralaba (STPW) untuk Penerima Waralaba Lanjutan dari Waralaba Luar Negeri'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '30', 'program_kode' => '2', 'kegiatan_kode' => '205', 'kegiatan_nama' => 'Penerbitan Surat Izin Usaha Perdagangan Minuman Beralkohol Golongan B dan C untuk Pengecer dan Penjual Langsung Minum di Tempat'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '30', 'program_kode' => '2', 'kegiatan_kode' => '206', 'kegiatan_nama' => 'Pengendalian Fasilitas Penyimpanan Bahan Berbahaya dan Pengawasan Distribusi, Pengemasan dan Pelabelan Bahan Berbahaya di Tingkat Daerah Kabupaten/ Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '30', 'program_kode' => '2', 'kegiatan_kode' => '207', 'kegiatan_nama' => 'Penerbitan Surat Keterangan Asal (Bagi Daerah Kabupaten/Kota yang Telah Ditetapkan sebagai Instansi Penerbit Surat Keterangan Asal)'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '30', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pembangunan dan Pengelolaan Sarana Distribusi Perdagangan'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '30', 'program_kode' => '3', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pembinaan Terhadap Pengelola Sarana Distribusi Perdagangan Masyarakat di Wilayah Kerjanya'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '30', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Menjamin Ketersediaan Barang Kebutuhan Pokok dan Barang Penting di Tingkat Daerah Kabupaten/ Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '30', 'program_kode' => '4', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pengendalian Harga, dan Stok Barang Kebutuhan Pokok dan Barang Penting di Tingkat Pasar Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '30', 'program_kode' => '4', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pengawasan Pupuk dan Pestisida Bersubsidi di Tingkat Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '30', 'program_kode' => '5', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyelenggaraan Promosi Dagang melalui Pameran Dagang dan Misi Dagang bagi Produk Ekspor Unggulan yang terdapat pada 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '30', 'program_kode' => '6', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pelaksanaan Metrologi Legal, Berupa Tera, Tera Ulang, dan Pengawasan'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '30', 'program_kode' => '7', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pelaksanaan Promosi, Pemasaran dan Peningkatan Penggunaan Produk Dalam Negeri'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '31', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyusunan dan Evaluasi Rencana Pembangunan Industri Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '31', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penerbitan Izin Usaha Industri (IUI), Izin Perluasan Usaha Industri (IPUI), Izin Usaha Kawasan Industri (IUKI) dan Izin Perluasan Kawasan Industri (IPKI) Kewenangan Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '31', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyediaan Informasi Industri untuk Informasi Industri untuk IUI, IPUI, IUKI dan IPKI Kewenangan Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '32', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pencadangan Tanah untuk Kawasan Transmigrasi'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '32', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penataan Persebaran Penduduk yang Berasal dari 1 (satu) Daerah Kabupaten/Kota'],
['permen_ver' => 1, 'urusan_kode' => '3', 'bidang_kode' => '32', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengembangan Satuan Permukiman pada Tahap Kemandirian'],
['permen_ver' => 1, 'urusan_kode' => '4', 'bidang_kode' => '1', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Administrasi Tata Pemerintahan'],
['permen_ver' => 1, 'urusan_kode' => '4', 'bidang_kode' => '1', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pelaksanaan Kebijakan Kesejahteraan Rakyat'],
['permen_ver' => 1, 'urusan_kode' => '4', 'bidang_kode' => '1', 'program_kode' => '2', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Fasilitasi dan Koordinasi Hukum'],
['permen_ver' => 1, 'urusan_kode' => '4', 'bidang_kode' => '1', 'program_kode' => '2', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Fasilitasi Kerjasama Daerah'],
['permen_ver' => 1, 'urusan_kode' => '4', 'bidang_kode' => '1', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pelaksanaan Kebijakan Perekonomian'],
['permen_ver' => 1, 'urusan_kode' => '4', 'bidang_kode' => '1', 'program_kode' => '3', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pelaksanaan Administrasi Pembangunan'],
['permen_ver' => 1, 'urusan_kode' => '4', 'bidang_kode' => '1', 'program_kode' => '3', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pengelolaan Pengadaan Barang dan Jasa'],
['permen_ver' => 1, 'urusan_kode' => '4', 'bidang_kode' => '1', 'program_kode' => '3', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Pemantauan Kebijakan Sumber Daya Alam'],
['permen_ver' => 1, 'urusan_kode' => '4', 'bidang_kode' => '2', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pembentukan Peraturan Daerah dan Peraturan DPRD'],
['permen_ver' => 1, 'urusan_kode' => '4', 'bidang_kode' => '2', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pembahasan Kebijakan Anggaran'],
['permen_ver' => 1, 'urusan_kode' => '4', 'bidang_kode' => '2', 'program_kode' => '2', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pengawasan Penyelenggaraan Pemerintahan'],
['permen_ver' => 1, 'urusan_kode' => '4', 'bidang_kode' => '2', 'program_kode' => '2', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Peningkatan Kapasitas DPRD'],
['permen_ver' => 1, 'urusan_kode' => '4', 'bidang_kode' => '2', 'program_kode' => '2', 'kegiatan_kode' => '205', 'kegiatan_nama' => 'Penyerapan dan Penghimpunan Aspirasi Masyarakat'],
['permen_ver' => 1, 'urusan_kode' => '4', 'bidang_kode' => '2', 'program_kode' => '2', 'kegiatan_kode' => '206', 'kegiatan_nama' => 'Pelaksanaan dan Pengawasan Kode Etik DPRD'],
['permen_ver' => 1, 'urusan_kode' => '4', 'bidang_kode' => '2', 'program_kode' => '2', 'kegiatan_kode' => '207', 'kegiatan_nama' => 'Pembahasan Kerja Sama Daerah'],
['permen_ver' => 1, 'urusan_kode' => '4', 'bidang_kode' => '2', 'program_kode' => '2', 'kegiatan_kode' => '208', 'kegiatan_nama' => 'Fasilitasi Tugas DPRD'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '1', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyusunan Perencanaan dan Pendanaan'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '1', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Analisis Data dan Informasi Pemerintahan Daerah Bidang Perencanaan Pembangunan Daerah'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '1', 'program_kode' => '2', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pengendalian, Evaluasi dan Pelaporan Bidang Perencanaan Pembangunan Daerah'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '1', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Koordinasi Perencanaan Bidang Pemerintahan dan Pembangunan Manusia'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '1', 'program_kode' => '3', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Koordinasi Perencanaan Bidang Perekonomian dan SDA (Sumber Daya Alam)'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '1', 'program_kode' => '3', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Koordinasi Perencanaan Bidang Infrastruktur dan Kewilayahan'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '2', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Koordinasi dan Penyusunan Rencana Anggaran Daerah'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '2', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Koordinasi dan Pengelolaan Perbendaharaan Daerah'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '2', 'program_kode' => '2', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Koordinasi dan Pelaksanaan Akuntansi dan Pelaporan Keuangan Daerah'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '2', 'program_kode' => '2', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Penunjang Urusan Kewenangan Pengelolaan Keuangan Daerah'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '2', 'program_kode' => '2', 'kegiatan_kode' => '205', 'kegiatan_nama' => 'Pengelolaan Data dan Implementasi Sistem Informasi Pemerintah Daerah Lingkup Keuangan Daerah'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '2', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengelolaan Barang Milik Daerah'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '2', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Kegiatan Pengelolaan pendapatan Daerah'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '3', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengadaan, Pemberhentian dan Informasi Kepegawaian ASN'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '3', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Mutasi dan Promosi ASN'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '3', 'program_kode' => '2', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pengembangan Kompetensi ASN'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '3', 'program_kode' => '2', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Penilaian dan Evaluasi Kinerja Aparatur'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '4', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Pengembangan Kompetensi Teknis'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '4', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Sertifikasi, Kelembagaan, Pengembangan Kompetensi Manajerial dan Fungsional'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '5', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penelitian dan Pengembangan Bidang Penyelenggaraan Pemerintahan dan Pengkajian Peraturan'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '5', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penelitian dan Pengembangan Bidang Sosial dan Kependudukan'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '5', 'program_kode' => '2', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Penelitian dan Pengembangan Bidang Ekonomi dan Pembangunan'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '5', 'program_kode' => '2', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Pengembangan Inovasi dan Teknologi'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '6', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Perencanaan dan Fasilitasi Kerja Sama'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '6', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pelaksanaan Kewilayahan Perbatasan'],
['permen_ver' => 1, 'urusan_kode' => '5', 'bidang_kode' => '6', 'program_kode' => '2', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Monitoring dan Evaluasi Kewilayahan Perbatasan'],
['permen_ver' => 1, 'urusan_kode' => '6', 'bidang_kode' => '1', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyelenggaraan Pengawasan Internal'],
['permen_ver' => 1, 'urusan_kode' => '6', 'bidang_kode' => '1', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penyelenggaraan Pengawasan dengan Tujuan Tertentu'],
['permen_ver' => 1, 'urusan_kode' => '6', 'bidang_kode' => '1', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Perumusan Kebijakan Teknis di Bidang Pengawasan dan Fasilitasi Pengawasan'],
['permen_ver' => 1, 'urusan_kode' => '6', 'bidang_kode' => '1', 'program_kode' => '3', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Pendampingan dan Asistensi'],
['permen_ver' => 1, 'urusan_kode' => '7', 'bidang_kode' => '1', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Koordinasi Penyelenggaraan Kegiatan Pemerintahan di Tingkat Kecamatan'],
['permen_ver' => 1, 'urusan_kode' => '7', 'bidang_kode' => '1', 'program_kode' => '2', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Penyelenggaraan Urusan Pemerintahan yang tidak Dilaksanakan oleh Unit Kerja Perangkat Daerah yang ada di Kecamatan'],
['permen_ver' => 1, 'urusan_kode' => '7', 'bidang_kode' => '1', 'program_kode' => '2', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Koordinasi Pemeliharaan Prasarana dan Sarana Pelayanan Umum'],
['permen_ver' => 1, 'urusan_kode' => '7', 'bidang_kode' => '1', 'program_kode' => '2', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Pelaksanaan Urusan Pemerintahan yang Dilimpahkan kepada Camat'],
['permen_ver' => 1, 'urusan_kode' => '7', 'bidang_kode' => '1', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Koordinasi Kegiatan Pemberdayaan Desa'],
['permen_ver' => 1, 'urusan_kode' => '7', 'bidang_kode' => '1', 'program_kode' => '3', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Kegiatan Pemberdayaan Kelurahan'],
['permen_ver' => 1, 'urusan_kode' => '7', 'bidang_kode' => '1', 'program_kode' => '3', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Pemberdayaan Lembaga Kemasyarakatan Tingkat Kecamatan'],
['permen_ver' => 1, 'urusan_kode' => '7', 'bidang_kode' => '1', 'program_kode' => '3', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Pemberdayaan Mukim'],
['permen_ver' => 1, 'urusan_kode' => '7', 'bidang_kode' => '1', 'program_kode' => '3', 'kegiatan_kode' => '205', 'kegiatan_nama' => 'Koordinasi dan Sinkronisasi Pemberlakuan Pembatasan Kegiatan Masyarakat (PPKM)'],
['permen_ver' => 1, 'urusan_kode' => '7', 'bidang_kode' => '1', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Koordinasi Upaya Penyelenggaraan Ketenteraman dan Ketertiban Umum'],
['permen_ver' => 1, 'urusan_kode' => '7', 'bidang_kode' => '1', 'program_kode' => '4', 'kegiatan_kode' => '202', 'kegiatan_nama' => 'Koordinasi Penerapan dan Penegakan Peraturan Daerah dan Peraturan Kepala Daerah'],
['permen_ver' => 1, 'urusan_kode' => '7', 'bidang_kode' => '1', 'program_kode' => '4', 'kegiatan_kode' => '203', 'kegiatan_nama' => 'Koordinasi Upaya Penyelenggaraan Ketentraman dan Ketertiban Umum'],
['permen_ver' => 1, 'urusan_kode' => '7', 'bidang_kode' => '1', 'program_kode' => '4', 'kegiatan_kode' => '204', 'kegiatan_nama' => 'Koordinasi Penerapan dan Penegakan Qanun dan Peraturan Kepala Daerah'],
['permen_ver' => 1, 'urusan_kode' => '7', 'bidang_kode' => '1', 'program_kode' => '5', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Penyelenggaraan Urusan Pemerintahan Umum sesuai Penugasan Kepala Daerah'],
['permen_ver' => 1, 'urusan_kode' => '7', 'bidang_kode' => '1', 'program_kode' => '6', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Fasilitasi, Rekomendasi dan Koordinasi Pembinaan dan Pengawasan Pemerintahan Desa'],
['permen_ver' => 1, 'urusan_kode' => '8', 'bidang_kode' => '1', 'program_kode' => '2', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Perumusan Kebijakan Teknis dan Pemantapan Pelaksanaan Bidang Ideologi Pancasila dan Karakter Kebangsaan'],
['permen_ver' => 1, 'urusan_kode' => '8', 'bidang_kode' => '1', 'program_kode' => '3', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Perumusan Kebijakan Teknis dan Pemantapan Pelaksanaan Bidang Pendidikan Politik, Etika Budaya Politik, Peningkatan Demokrasi, Fasilitasi Kelembagaan Pemerintahan, Perwakilan dan Partai Politik, Pemilihan Umum/Pemilihan Umum Kepala Daerah, serta Pemantauan Situasi Politik'],
['permen_ver' => 1, 'urusan_kode' => '8', 'bidang_kode' => '1', 'program_kode' => '4', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Perumusan Kebijakan Teknis dan Pemantapan Pelaksanaan Bidang Pemberdayaan dan Pengawasan Organisasi Kemasyarakatan'],
['permen_ver' => 1, 'urusan_kode' => '8', 'bidang_kode' => '1', 'program_kode' => '5', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Perumusan Kebijakan Teknis dan Pemantapan Pelaksanaan Bidang Ketahanan Ekonomi, Sosial dan Budaya'],
['permen_ver' => 1, 'urusan_kode' => '8', 'bidang_kode' => '1', 'program_kode' => '6', 'kegiatan_kode' => '201', 'kegiatan_nama' => 'Perumusan Kebijakan Teknis dan Pelaksanaan Pemantapan Kewaspadaan Nasional dan Penanganan Konflik Sosial'],

				]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('ref_kegiatan');
    }
}
